services:
  server:
    container_name: shogihome-lab
    image: shogihome-lab:latest
    build: .
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:8140"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
