export enum AppState {
  NORMAL = "normal",
  PASTE_DIALOG = "pasteDialog",
  POSITION_EDITING_DIALOG = "positionEditingDialog",
  EXPORT_POSITION_IMAGE_DIALOG = "exportBoardImageDialog",
  GAME_DIALOG = "gameDialog",
  GAME = "game",
  ANALYSIS = "analysis",
  ANALYSIS_DIALOG = "analysisDialog",
  MATE_SEARCH = "mateSearch",
  MATE_SEARCH_DIALOG = "mateSearchDialog",
  USI_ENGINES_DIALOG = "usiEnginesDialog",
  RECORD_FILE_HISTORY_DIALOG = "recordFileHistoryDialog",
  BATCH_CONVERSION_DIALOG = "batchConversionDialog",
  LOAD_REMOTE_FILE_DIALOG = "loadRemoteFileDialog",
  SHARE_DIALOG = "shareDialog",
  ADD_BOOK_MOVES_DIALOG = "addBookMovesDialog",
  SERVER_KIFU_DIALOG = "serverKifuDialog",
  BOOK_SELECT_DIALOG = "bookSelectDialog",
  DUPLICATE_POSITIONS_DIALOG = "duplicatePositionsDialog",
  SEARCH_DUPLICATE_POSITIONS_DIALOG = "searchDuplicatePositionsDialog",
  VISION_SCAN_DIALOG = "visionScanDialog",
  VISION_POSITION_EDIT_DIALOG = "visionPositionEditDialog",
  ELAPSED_TIME_CHART_DIALOG = "elapsedTimeChartDialog",
  PUZZLE = "puzzle",
}

export enum ResearchState {
  IDLE = "idle",
  STARTUP_DIALOG = "startupDialog",
  STOPPING = "stopping",
  RUNNING = "running",
  PAUSED = "paused",
}
